- name: TAKE A SNAPSHOT OF THE DEVICE
  hosts: testhost
  tasks:
    - name: Print all Facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: GET CONFIGURATION AND STATE OUTPUTs
      cisco.ios.ios_command:
        commands:
          - show run
          - show inventory
      register: entire_output

    - debug:
        var: entire_output

    - local_action: 
        module: copy 
        content: "{{ ansible_facts['net_hostname'] }}.json"
        dest: ./host_out.txt
    
    - name: Copy ansible facts to a file
      copy:
        content: "{{ ansible_facts }}"
        dest: ./{{ ansible_facts['net_hostname'] }}.json