name: Ansible CD

on:
  workflow_dispatch:

jobs:
  ansible-workflow:
    runs-on: ubuntu-latest
    name: Ansible CD
    continue-on-error: false
    env:
      CISCO_USER: ${{ secrets.CISCO_USER }}
      CISCO_PASSWORD: ${{ secrets.CISCO_PASSWORD }}
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Ansible
        run: |
          python3 -m pip install ansible
          python3 -m pip install ansible-pylibssh paramiko
          ansible --version

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            !.github
            !.config
            !*.md

      - name: Set ansible hosts
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          sudo mkdir /etc/ansible
          sudo cp deploy/hosts /etc/ansible/hosts
          sudo mkdir -p ./snapshots
          sudo chmod -R a+rw ./snapshots

      - name: Show deployment files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Below yaml files will be executed:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo $file
            fi
          done

      - name: Deploy
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          
          echo "Below yaml files will be executed:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo "Executing $file"
              ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook $file
            fi
          done

      - name: Commit facts output
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions