name: Ansible Workflow

on:  
  push:
  pull_request:

jobs:
  ansible-workflow:
    runs-on: ubuntu-latest
    name: Ansible CICD
    continue-on-error: false
    env:
      CISCO_USER: ${{ secrets.CISCO_USER }}
      CISCO_PASSWORD: ${{ secrets.CISCO_PASSWORD }}
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Ansible
        run: |
          python3 -m pip install ansible
          python3 -m pip install ansible-pylibssh paramiko
          ansible --version

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            !.github
            !.config
            !snapshot.yml
            !*.md

      - name: Show changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Below yaml files are changed:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo $file
            fi
          done

      - name: Show changed files diffs
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo "Generating diff for $file"
              git diff HEAD~1 $file
            fi
          done

      - name: Set ansible hosts
        run: |
          sudo mkdir /etc/ansible
          sudo cp deploy/hosts /etc/ansible/hosts

      - name: Lint
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ansible/ansible-lint-action@v6.10.2

      - name: Dry-run
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo "Executing dry-run for $file"
              ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook $file --check -v
            fi
          done

      - name: Show Deploy files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Below yaml files will be executed:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo $file
            fi
          done

      - name: Deploy
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Below yaml files will be executed:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo "Executing $file"
              ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook $file
            fi
          done

      - name: Collect the facts
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook snapshot.yml
          cat host_out.txt

      - name: Read host name output
        if: steps.changed-files.outputs.any_changed == 'true'
        id: host_out
        uses: juliangruber/read-file-action@v1
        with:
          path: ./host_out.txt
      - name: Show check-in file
        run: |
          echo "Following file will be checked-in"
          echo "${{ steps.host_out.outputs.content }}"
          echo "content"
          cat ${{ steps.host_out.outputs.content }}