name: Ansible CI

on:  
  push:
  pull_request:

jobs:
  ansible-workflow:
    runs-on: ubuntu-latest
    name: Ansible CI
    continue-on-error: false
    env:
      CISCO_USER: ${{ secrets.CISCO_USER }}
      CISCO_PASSWORD: ${{ secrets.CISCO_PASSWORD }}
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Ansible
        run: |
          python3 -m pip install ansible
          python3 -m pip install ansible-pylibssh paramiko
          ansible --version

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            !.github
            !.config
            !*.md

      - name: Show changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Below yaml files are changed:"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo $file
            fi
          done

      - name: Show changed files diffs
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo "Generating diff for $file"
              git diff HEAD~1 $file
            fi
          done

      - name: Set ansible hosts
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          sudo mkdir /etc/ansible
          sudo cp deploy/hosts /etc/ansible/hosts
          sudo mkdir -p ./snapshots

      - name: Lint
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ansible/ansible-lint-action@v6.10.2

      - name: Dry-run
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ext="${file##*.}"
            if [ $ext == yml ] || [ $ext = yaml ]; then
              echo "Executing dry-run for $file"
              ANSIBLE_HOST_KEY_CHECKING=False ANSIBLE_STDOUT_CALLBACK=yaml ansible-playbook $file --check -v
            fi
          done